### ISSUE TITLE
Cannot dump XR Bootloader or settings

### ISSUE THREAD

**Issue by SadLittleOctopus** [rewheel-app/rewheel#35]
My XR: 4212 hardware, came with firmware 4150.
I flashed the backup extractor, and clicked dump bootloader. Progress never passed 0%. I retried with the dump settings option.
I need to be able to reflash my board with 4150 hardware to ride it again, but it's not available on the extras tab.
I tried flashing the closest available version, 4142. Board turns on and light flashes showing battery indication as usual. Trying to mount the board puts it in an error state and trying to connect with the official app is impossible (it disconnects, unreliable bluetooth).
I reconnected with rewheel and reflashed the extractor, knowing I can get the board to want to accept a firmware update.
Reconnect with onewheel app to the "firmware update required" notice, trying to download the update from FM immediately fails every time.
![image](https://user-images.githubusercontent.com/55313133/212202591-4b238e54-e8f3-4187-a60e-a5e499663310.png)

I would like to be able to reflash the 4150 firmware if possible. I have another XR with firmware 4155 hardware 4212, but I can't read cell voltages from it.

Watching the videos posted yesterday, I know outlandnish said that XR compatibility with current development was limited, but the site today looks different from the version he had on the video, and when I connected my Pint X, I was notified that backup was not available for it. This made me believe that I could successfully continue past the warnings and remove the bluetooth handshake that always annoys me.

**Comment by outlandnish** [comment]
Discussed on Discord, needs investigation with an XR controller. The website has been updated to also not allow XRs to use the extractor for now.

Closing this issue too
