### ISSUE TITLE
Different hardware version after flashing

### ISSUE THREAD

**Issue by sonph** [rewheel-app/rewheel#58]
I have an OG pint with FW 5050 HW 5314. After flashing patched FW 5040 I noticed that HW version is now 5312. This is the same board and controller. Is this expected?

**Comment by sonph** [comment]
Before flashing:
<img src="https://user-images.githubusercontent.com/2466660/216235215-8e01b273-4618-4e56-b776-86740cd45f48.JPEG" width="30%">

After flashing:
<img src="https://user-images.githubusercontent.com/2466660/216235210-604391c0-cea7-4bd6-8ba7-abaa2d5cb796.JPEG" width="30%">

**Comment by outlandnish** [comment]
It's not intended behavior but we've noticed that happening. Interestingly, if you go back to 5046 / 5050, the version number reverts back to 5314. Not sure why it shows up as such (maybe the way they were loading the hardware rev in older firmware is different)

**Comment by Mattb1313** [comment]
A friend tried to install rewheel.app on my og pint as a "surprise" now it isnt working at all. Any help would be greatly appreciated.
