### ISSUE TITLE
Fill box text overlays bottom navigation bar

### ISSUE THREAD

**Issue by yourjelly** [rewheel-app/rewheel#77]
Minor visual bug

![image](https://user-images.githubusercontent.com/26312697/229590938-85c6b2e1-5d39-497c-b4f1-e05010553fc0.png)

![image](https://user-images.githubusercontent.com/26312697/229591464-69fd8855-c391-499d-be67-4a048158dfe4.png)

**Comment by outlandnish** [comment]
Thanks for the heads up! We'll open a PR for that soonish. (Or feels free to contribute the fix :))

**Comment by yourjelly** [comment]
I'd need to do more research to figure out how to fix it.
But I found that we can either disable the z-index:1; on the input label
or add z-index:2; to the bottom navigation

**Comment by ssteuteville** [comment]
> Thanks for the heads up! We'll open a PR for that soonish. (Or feels free to contribute the fix :))

@outlandnish I want to start giving back, don't have a lot of experience with the firmware side of things, but a lot of experience building UIs, especially with the libraries you guys use!

I'm going to PR this soon, if it were my project, i'd prob change the layout a bit and introduce a side nav for this on larger screens. If you want me to keep it simple and just fix the bug without changing the UX I can do that though. Let me know!

**Comment by outlandnish** [comment]
Feel free to add the side nav for larger screens! I haven't had time to look at the code in a couple of weeks now. Any UI improvements are welcome because I haven't put the proper time into it myself

**Comment by ssteuteville** [comment]
@yourjelly yep, been doing this a long time lol..

The other option would've been to re-do the layout of the page. Typically what i do is a calculate the height of the page and subtract the header/footer height from it and use that for the height of the content.. kinda brittle tho if u don't get it right

**Comment by ssteuteville** [comment]
@yourjelly if you want to test my changes they are here: https://deploy-preview-81--rewheel-app.netlify.app/

**Comment by yourjelly** [comment]
@ssteuteville Looks good, not to fuck with your scope, but this might be a good opportunity to extract the key extractor to its own tab creating a top to bottom workflow instead of the back and forth it is now.
Only risk I see of that is confusing people following the videos, but with the OTA's less accessible the pings about that have receded.
![image](https://user-images.githubusercontent.com/26312697/234936680-09d169c1-ec90-4a29-8135-73ac48cbc18d.png)

**Comment by ssteuteville** [comment]
@outlandnish just out of curiosity, I saw the main pipeline ran after u merged, when could we expect to see this in production?

**Comment by ssteuteville** [comment]
> @ssteuteville Looks good, not to fuck with your scope, but this might be a good opportunity to extract the key extractor to its own tab creating a top to bottom workflow instead of the back and forth it is now. Only risk I see of that is confusing people following the videos, but with the OTA's less accessible the pings about that have receded. 

I'd defer to @outlandnish on any enhancements that could be made! If there is stuff on the web side of all of this I could prob spend an hour or two a week iterating on the UX! Just create enhancement issues or something and I'll check occasionally.
