### ISSUE TITLE
Rewheel.app problems

### ISSUE THREAD

**Issue by Mattb1313** [rewheel-app/rewheel#78]
A friend tried to install rewheel.app on my og pint as a "surprise" while borrowing my board one evening. Now it isn't operational at all. Any help would be much appreciated, as this is my daily ride to work and around town. Thanks

**Comment by outlandnish** [comment]
Sorry, issues here are with the functionality of the Rewheel web app, not board issues. Please post on Discord for help with that and provide more detail as to what's wrong with your board / what steps were done to get there.

Closing this issue.
