### ISSUE TITLE
Mod Request: posi-implementation

### ISSUE THREAD

**Issue by yourjelly** [rewheel-app/rewheel#79]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/rewheel-app/rewheel/issues/79)

Posi on sensor start and revert to dual zone for riding.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/rewheel-app/rewheel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by Tbruno25** [comment]
I'm currently giving this a shot :+1:

**Comment by PopPopBen** [comment]
SureStart's descriptions of the features. 

Standard SureStart Includes:
Single Zone Sensor Startup - Program your 2-zone sensor to act as a larger 1-zone sensor upon startup, then after a selected amount of time (1-15 seconds) it will automatically revert back to a 2-zone sensor so you can heel-lift dismount.

Pro SureStart Includes:
AirSense - Keeps the sensor engaged during drops or jumps so the board can’t shut off mid-air. Reverts to standard posi mode upon landing. AirSense monitors speed and keeps posi mode engaged when going faster than 5 mph. When you drop below 5 mph, posi mode times out after 1 second. This mitigates sensor disengagements while mid-air when the wheel suddenly slows down to 0.

Deactivation Delay - When you come off the board during a jump or ripping through chunky terrain, the sensor stays on longer to keep the motor engaged. Deactivation Delay can be customized from 100 to 2000 milliseconds (0.1 - 1 second).

Single Zone Sensor Startup - Program your 2-zone sensor to act as a larger 1-zone sensor upon startup, then after a selected amount of time (1-15 seconds) it will automatically revert back to a 2-zone sensor so you can heel-lift dismount.

**Comment by yourjelly** [comment]
Hey @PopPopBen we want to avoid copyright issues with this project, so copy pasting text from someone else's product is not okay. Please restate your expectations for the mod in your own words.

**Comment by MitchellHayes** [comment]
Standard Features:
Unified Zone Sensor Startup: Configure your dual-zone sensor to function as a single, larger zone sensor during startup. After a chosen duration (1-15 seconds), it will automatically switch back to a 2-zone sensor, enabling heel-lift dismounting.
Pro SureStart Features:

Advanced Features:
Air-Time Recognition: This feature maintains sensor engagement during drops or jumps, preventing the board from shutting off mid-air. Upon landing, it reverts to the standard posi mode. AirSense also monitors speed, maintaining posi mode engagement when traveling above 5 mph. If the speed drops below 5 mph, posi mode deactivates after a 1-second timeout, reducing the likelihood of sensor disengagement during mid-air wheel slowdowns.

Deactivation Delay: The sensor remains active for an extended period to keep the motor engaged when you leave the board during a jump or while navigating uneven terrain. You can customize the Deactivation Delay between 100 and 2000 milliseconds (0.1 - 1 second).

Unified Zone Sensor Startup: Configure your dual-zone sensor to function as a single, larger zone sensor during startup. After a chosen duration (1-15 seconds), it will automatically switch back to a 2-zone sensor, enabling heel-lift dismounting.

**Comment by yourjelly** [comment]
> 100 and 2000 milliseconds (0.1 - 1 second).
Thanks, I will note that 2000ms is 2 seconds

**Comment by MitchellHayes** [comment]
> > 100 and 2000 milliseconds (0.1 - 1 second).
> 
> Thanks, I will note that 2000ms is 2 seconds

thanks updated... numbers are hard

**Comment by MitchellHayes** [comment]
It looks like ticket #82 only handles single zone activation and a delay to returning to dual zone, this doesn't address the air time functionality of delaying deactivation when in the air and either or both sensors disengage.

**Comment by exPHAT** [comment]
@MitchellHayes It increases time for mid-air activation via its first instruction patch. You can change the `cmp.w` comparison I wrote to make it longer. https://github.com/rewheel-app/rewheel/pull/82/files#diff-7281cf1aaf55489e5c137d9c39462c84016dd9fbac590d5b8a2e826e08983558R99
